# Generated by Django 5.1.3 on 2024-12-13 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_id', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('hod_id', models.CharField(max_length=255, null=True)),
                ('hod_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=200, null=True)),
                ('hod', models.CharField(max_length=200, null=True)),
                ('about', models.TextField()),
                ('display_order', models.CharField(max_length=255, null=True)),
                ('created', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='scientific_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('department', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('image_name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('fax', models.CharField(max_length=200, null=True)),
                ('academic_background', models.TextField()),
                ('professional_experience', models.TextField()),
                ('research_interests', models.TextField()),
                ('awards_achievements', models.TextField()),
                ('publications', models.TextField()),
                ('projects', models.TextField()),
                ('research_staff', models.CharField(max_length=255, null=True)),
                ('display_order', models.CharField(max_length=255, null=True)),
                ('active', models.CharField(max_length=200, null=True)),
                ('created', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
