# Generated by Django 5.1.3 on 2024-12-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_advertise_alumini_appointment_award_bgrc_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
