# Generated by Django 5.1.3 on 2024-12-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
