# Generated by Django 5.1.3 on 2024-12-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_departments_data_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department_staff',
            old_name='department_name',
            new_name='hod_name',
        ),
    ]
