# Generated by Django 5.1.3 on 2024-12-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_department_dept_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_info',
            new_name='department_info',
        ),
    ]
