# Generated by Django 5.1.3 on 2024-12-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_rename_dept_info_department_department_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='about_research',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='research_projects',
            field=models.TextField(null=True),
        ),
    ]
