# Generated by Django 5.1.3 on 2024-12-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_departments_about_research_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='about_department',
        ),
        migrations.AddField(
            model_name='departments',
            name='about_department1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='about_department2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='about_department3',
            field=models.TextField(null=True),
        ),
    ]
