# Generated by Django 5.1.3 on 2025-01-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_departments_about_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('department_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, null=True)),
                ('department', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
