# Generated by Django 5.1.3 on 2025-01-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_admin_staff_staff_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=255, null=True)),
                ('department_name', models.CharField(max_length=255, null=True)),
                ('hod_id', models.CharField(max_length=255, null=True)),
                ('hod_name', models.CharField(max_length=255, null=True)),
                ('department_info', models.CharField(max_length=255, null=True)),
                ('about_department1', models.TextField(null=True)),
                ('about_department2', models.TextField(null=True)),
                ('about_department3', models.TextField(null=True)),
                ('about_research', models.TextField(null=True)),
                ('research_projects', models.TextField(null=True)),
                ('staff_designation', models.CharField(max_length=255, null=True)),
                ('staff_email', models.EmailField(max_length=255, null=True)),
                ('staff_display_order', models.CharField(max_length=255, null=True)),
                ('display_order', models.CharField(max_length=255, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
