# Generated by Django 5.1.3 on 2025-01-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_dept_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='department_staff',
        ),
        migrations.DeleteModel(
            name='departments',
        ),
    ]
