# Generated by Django 5.1.3 on 2025-01-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_delete_department_delete_department_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(unique=True)),
                ('department_name', models.CharField(max_length=255)),
                ('hod_id', models.IntegerField()),
                ('hod_name', models.CharField(max_length=255)),
                ('department_type', models.CharField(choices=[('scientific', 'Scientific'), ('nonscientific', 'Non Scientific')], max_length=50)),
                ('about_department', models.TextField()),
                ('about_department1', models.TextField(blank=True)),
                ('about_department2', models.TextField(blank=True)),
                ('about_department3', models.TextField(blank=True)),
                ('about_research', models.TextField(blank=True)),
                ('research_projects', models.TextField(blank=True)),
                ('staff_designation', models.CharField(max_length=255)),
                ('staff_email', models.EmailField(max_length=254)),
                ('staff_display_order', models.IntegerField(blank=True, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
