# Generated by Django 5.1.3 on 2025-01-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='about_department',
            new_name='department_info',
        ),
        migrations.RemoveField(
            model_name='department',
            name='about_department1',
        ),
        migrations.RemoveField(
            model_name='department',
            name='about_department2',
        ),
        migrations.RemoveField(
            model_name='department',
            name='about_department3',
        ),
        migrations.RemoveField(
            model_name='department',
            name='about_research',
        ),
        migrations.RemoveField(
            model_name='department',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='department',
            name='research_projects',
        ),
        migrations.RemoveField(
            model_name='department',
            name='staff_designation',
        ),
        migrations.RemoveField(
            model_name='department',
            name='staff_display_order',
        ),
        migrations.RemoveField(
            model_name='department',
            name='staff_email',
        ),
        migrations.AddField(
            model_name='department',
            name='department_ab1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_ab2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_ab3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_abrs',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_do',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_rp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_stde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_stdo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_stemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('scientific', 'Scientific'), ('non_scientific', 'Non-Scientific')], default='scientific', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='hod_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='hod_name',
            field=models.CharField(max_length=200),
        ),
    ]
