# Generated by Django 5.1.3 on 2025-01-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_rename_about_department_department_department_info_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='department_info',
        ),
    ]
