# Generated by Django 5.1.3 on 2025-01-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_delete_department_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept_info',
            old_name='department_id',
            new_name='nonscientific_department_id',
        ),
        migrations.RenameField(
            model_name='dept_info',
            old_name='department_name',
            new_name='nonscientific_department_name',
        ),
        migrations.RenameField(
            model_name='dept_info',
            old_name='hod_id',
            new_name='nonscientific_hod_id',
        ),
        migrations.RenameField(
            model_name='dept_info',
            old_name='hod_name',
            new_name='nonscientific_hod_name',
        ),
        migrations.AddField(
            model_name='dept_info',
            name='scientific_department_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dept_info',
            name='scientific_department_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dept_info',
            name='scientific_hod_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dept_info',
            name='scientific_hod_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
