# Generated by Django 5.1.3 on 2025-01-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_rename_department_id_dept_info_nonscientific_department_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept_info',
            old_name='nonscientific_department_id',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='dept_info',
            old_name='nonscientific_department_name',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='dept_info',
            old_name='nonscientific_hod_id',
            new_name='hod_id',
        ),
        migrations.RenameField(
            model_name='dept_info',
            old_name='nonscientific_hod_name',
            new_name='hod_name',
        ),
        migrations.RemoveField(
            model_name='dept_info',
            name='scientific_department_id',
        ),
        migrations.RemoveField(
            model_name='dept_info',
            name='scientific_department_name',
        ),
        migrations.RemoveField(
            model_name='dept_info',
            name='scientific_hod_id',
        ),
        migrations.RemoveField(
            model_name='dept_info',
            name='scientific_hod_name',
        ),
    ]
