# Generated by Django 5.1.3 on 2025-01-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_rename_nonscientific_department_id_dept_info_department_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='support_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=255, null=True)),
                ('department_name', models.CharField(max_length=255, null=True)),
                ('hod_id', models.CharField(max_length=255, null=True)),
                ('hod_name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
