# Generated by Django 5.1.3 on 2025-01-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_support_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_new',
            old_name='on_going',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='project_new',
            name='scientist_id',
        ),
        migrations.AddField(
            model_name='project_new',
            name='project_date',
            field=models.DateTimeField(null=True),
        ),
    ]
