# Generated by Django 5.1.3 on 2025-01-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_rename_on_going_project_new_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientific_staff',
            old_name='display_order',
            new_name='profilepic_name',
        ),
        migrations.RenameField(
            model_name='scientific_staff',
            old_name='image_name',
            new_name='scientist_id',
        ),
        migrations.RenameField(
            model_name='scientific_staff',
            old_name='staff_name',
            new_name='scientist_name',
        ),
        migrations.AddField(
            model_name='scientific_staff',
            name='alt_email_id',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
