# Generated by Django 5.1.3 on 2025-01-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_rename_display_order_scientific_staff_profilepic_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientific_staff',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
