# Generated by Django 5.1.3 on 2025-01-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_alter_scientific_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientific_staff',
            name='alt_email_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scientific_staff',
            name='email_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
