# Generated by Django 5.1.3 on 2025-01-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_remove_dept_info_display_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept_info',
            name='research_projects',
        ),
    ]
