# Generated by Django 5.1.3 on 2025-01-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_remove_dept_info_research_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept_info',
            old_name='department_name',
            new_name='lab_department_name',
        ),
    ]
