# Generated by Django 5.1.3 on 2025-01-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_rename_department_name_dept_info_lab_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept_info',
            name='department_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
