# Generated by Django 5.1.3 on 2025-01-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_dept_info_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept_info',
            old_name='hod_name',
            new_name='scientist_name',
        ),
    ]
