# Generated by Django 5.1.3 on 2025-01-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_rename_hod_name_dept_info_scientist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_info',
            name='department_info',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
