# Generated by Django 5.1.3 on 2025-01-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_alter_dept_info_department_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project_new',
            new_name='projects',
        ),
    ]
