# Generated by Django 5.1.3 on 2025-01-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_rename_project_new_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
