# Generated by Django 5.1.3 on 2025-01-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_alter_projects_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_incharge',
            new_name='scientist_name',
        ),
    ]
