# Generated by Django 5.1.3 on 2025-01-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_rename_project_incharge_projects_scientist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='status',
            new_name='project_status',
        ),
    ]
