# Generated by Django 5.1.3 on 2025-01-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_rename_status_projects_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
