# Generated by Django 5.1.3 on 2025-01-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_rename_support_department_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_designation',
            old_name='department',
            new_name='category',
        ),
    ]
