# Generated by Django 5.1.3 on 2025-01-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_rename_department_staff_designation_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_designation',
            old_name='category',
            new_name='category_name',
        ),
    ]
