# Generated by Django 5.1.3 on 2025-01-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_rename_department_name_projects_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientific_staff',
            old_name='department_name',
            new_name='aadhar_no',
        ),
        migrations.RenameField(
            model_name='scientific_staff',
            old_name='research_staff',
            new_name='alt_phone_no',
        ),
        migrations.RenameField(
            model_name='scientific_staff',
            old_name='status',
            new_name='author_name',
        ),
        migrations.RemoveField(
            model_name='scientific_staff',
            name='awards_achievements',
        ),
        migrations.RemoveField(
            model_name='scientific_staff',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='scientific_staff',
            name='publications',
        ),
        migrations.AddField(
            model_name='scientific_staff',
            name='category_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scientific_staff',
            name='guide_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scientific_staff',
            name='join_year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scientific_staff',
            name='level_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scientific_staff',
            name='profile_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
