# Generated by Django 5.1.3 on 2025-01-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_rename_department_name_scientific_staff_aadhar_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientific_staff',
            old_name='profile_status',
            new_name='status',
        ),
    ]
