# Generated by Django 5.1.3 on 2025-01-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_rename_profile_status_scientific_staff_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientific_staff',
            old_name='status',
            new_name='profile_status',
        ),
    ]
