# Generated by Django 5.1.3 on 2025-01-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_rename_status_scientific_staff_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientific_staff',
            name='lab_department_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
