# Generated by Django 5.1.3 on 2025-01-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_scientific_staff_lab_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientific_staff',
            name='guide_name',
        ),
    ]
