# Generated by Django 5.1.3 on 2025-01-22 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_remove_scientific_staff_guide_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='admin_user',
            name='last_name',
        ),
    ]
