# Generated by Django 5.1.3 on 2025-01-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_rename_first_name_admin_user_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_staff',
        ),
    ]
