# Generated by Django 5.1.3 on 2025-01-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_delete_admin_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_user',
            old_name='user_name',
            new_name='username',
        ),
    ]
