# Generated by Django 5.1.3 on 2025-01-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_rename_user_name_admin_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='support_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_dept_id', models.CharField(max_length=255, null=True)),
                ('sup_dept_name', models.CharField(max_length=255, null=True)),
                ('sup_hod_name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
