# Generated by Django 5.1.3 on 2025-01-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_rename_sup_dept_id_support_department_support_department_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminnistration_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=255, null=True)),
                ('admin_name', models.CharField(max_length=255, null=True)),
                ('support_department_name', models.CharField(max_length=255, null=True)),
                ('category_name', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('email_id', models.CharField(max_length=200, null=True)),
                ('alt_email_id', models.CharField(max_length=200, null=True)),
                ('profilepic_name', models.CharField(max_length=255, null=True)),
                ('phone_no', models.CharField(max_length=255, null=True)),
                ('fax_no', models.CharField(max_length=255, null=True)),
                ('alt_phone_no', models.CharField(max_length=255, null=True)),
                ('level_no', models.CharField(max_length=255, null=True)),
                ('aadhar_no', models.CharField(max_length=255, null=True)),
                ('join_year', models.CharField(max_length=255, null=True)),
                ('academic_background', models.TextField()),
                ('specialization', models.TextField()),
                ('professional_experience', models.TextField()),
                ('profile_status', models.CharField(max_length=255, null=True)),
                ('data_created', models.DateTimeField(null=True)),
            ],
        ),
    ]
