# Generated by Django 5.1.3 on 2025-01-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_adminnistration_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminnistration_staff',
            new_name='administration_staff',
        ),
    ]
