# Generated by Django 5.1.3 on 2025-01-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_technical_staff_rename_publication_copy_publications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technical_staff',
            old_name='tech_id',
            new_name='technical_id',
        ),
        migrations.RenameField(
            model_name='technical_staff',
            old_name='tech_name',
            new_name='technical_name',
        ),
    ]
