# Generated by Django 5.1.3 on 2025-01-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0052_rename_tech_id_technical_staff_technical_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointment',
        ),
        migrations.DeleteModel(
            name='committee',
        ),
        migrations.DeleteModel(
            name='cv_photo',
        ),
        migrations.DeleteModel(
            name='departments_test',
        ),
        migrations.DeleteModel(
            name='icc_women',
        ),
        migrations.DeleteModel(
            name='instrument',
        ),
        migrations.DeleteModel(
            name='library',
        ),
        migrations.DeleteModel(
            name='login_data',
        ),
        migrations.DeleteModel(
            name='niih_projects',
        ),
        migrations.DeleteModel(
            name='niih_publications',
        ),
        migrations.DeleteModel(
            name='niih_staff',
        ),
        migrations.DeleteModel(
            name='out_publications',
        ),
        migrations.DeleteModel(
            name='publications',
        ),
        migrations.DeleteModel(
            name='staff_new',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
