# Generated by Django 5.1.3 on 2025-01-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0054_appointment_committee_cv_photo_departments_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='publications_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_id', models.CharField(max_length=255, null=True)),
                ('publication_author_name', models.CharField(max_length=255, null=True)),
                ('publication_title', models.CharField(max_length=255, null=True)),
                ('publication_journal_name', models.CharField(max_length=255, null=True)),
                ('publication_type', models.CharField(max_length=255, null=True)),
                ('publication_status', models.CharField(max_length=255, null=True)),
                ('publication_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='appointment',
        ),
        migrations.DeleteModel(
            name='committee',
        ),
        migrations.DeleteModel(
            name='cv_photo',
        ),
        migrations.DeleteModel(
            name='departments_test',
        ),
        migrations.DeleteModel(
            name='icc_women',
        ),
        migrations.DeleteModel(
            name='instrument',
        ),
        migrations.DeleteModel(
            name='library',
        ),
        migrations.DeleteModel(
            name='login_data',
        ),
        migrations.DeleteModel(
            name='niih_projects',
        ),
        migrations.DeleteModel(
            name='niih_publications',
        ),
        migrations.DeleteModel(
            name='niih_staff',
        ),
        migrations.DeleteModel(
            name='out_publications',
        ),
        migrations.DeleteModel(
            name='staff_new',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
