# Generated by Django 5.1.3 on 2025-01-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0055_publications_list_delete_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bulletin_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin_id', models.CharField(max_length=255, null=True)),
                ('bulletin_name', models.CharField(max_length=255, null=True)),
                ('vol_no', models.CharField(max_length=255, null=True)),
                ('bulletin_start_month', models.CharField(max_length=255, null=True)),
                ('bulletin_end_month', models.CharField(max_length=255, null=True)),
                ('bulletin_year', models.CharField(max_length=255, null=True)),
                ('bulletin_file_name', models.CharField(max_length=300, null=True)),
                ('data_created', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='bulletin',
        ),
    ]
