# Generated by Django 5.1.3 on 2025-01-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0057_remove_bulletin_list_bulletin_end_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletin_list',
            old_name='bulletin_name',
            new_name='bulletin_title',
        ),
    ]
