# Generated by Django 5.1.3 on 2025-01-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0058_rename_bulletin_name_bulletin_list_bulletin_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin_list',
            name='bulletin_month',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
