# Generated by Django 5.1.3 on 2025-01-29 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0059_bulletin_list_bulletin_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletin_list',
            old_name='data_created',
            new_name='bulletin_date',
        ),
    ]
