# Generated by Django 5.1.3 on 2025-01-29 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0060_rename_data_created_bulletin_list_bulletin_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletin_list',
            old_name='vol_no',
            new_name='bulletin_vol_no',
        ),
    ]
