# Generated by Django 5.1.3 on 2025-01-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0061_rename_vol_no_bulletin_list_bulletin_vol_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin_list',
            name='bulletin_date',
        ),
    ]
