# Generated by Django 5.1.3 on 2025-01-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0062_remove_bulletin_list_bulletin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin_list',
            name='bulletin_year',
            field=models.DateTimeField(null=True),
        ),
    ]
