# Generated by Django 5.1.3 on 2025-02-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0063_alter_bulletin_list_bulletin_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgrc_news',
            old_name='bgrc_news_month',
            new_name='newsletter_id',
        ),
        migrations.RenameField(
            model_name='bgrc_news',
            old_name='bgrc_news_name',
            new_name='newsletter_month',
        ),
        migrations.RenameField(
            model_name='bgrc_news',
            old_name='bgrc_news_year',
            new_name='newsletter_title',
        ),
        migrations.RenameField(
            model_name='bgrc_news',
            old_name='vol_no',
            new_name='newsletter_vol_no',
        ),
        migrations.RenameField(
            model_name='bgrc_news',
            old_name='data_created',
            new_name='newsletter_year',
        ),
    ]
