# Generated by Django 5.1.3 on 2025-02-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0064_rename_bgrc_news_month_bgrc_news_newsletter_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bgrc_news',
            new_name='newsletter_list',
        ),
    ]
