# Generated by Django 5.1.3 on 2025-02-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0065_rename_bgrc_news_newsletter_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='award',
            new_name='award_list',
        ),
        migrations.RenameField(
            model_name='award_list',
            old_name='user_name',
            new_name='scientist_name',
        ),
    ]
