# Generated by Django 5.1.3 on 2025-02-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0066_rename_award_award_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientific_staff',
            name='orcid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
