# Generated by Django 5.1.3 on 2025-02-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0067_scientific_staff_orcid'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_staff_id', models.CharField(max_length=255, null=True)),
                ('project_staff_name', models.CharField(max_length=255, null=True)),
                ('project_staff_departmernt', models.CharField(max_length=255, null=True)),
                ('project_staff_designation', models.CharField(max_length=255, null=True)),
                ('profile_status', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
