# Generated by Django 5.1.3 on 2025-02-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0069_alter_project_staff_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_staff',
            name='profile_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
