# Generated by Django 5.1.3 on 2025-02-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0070_alter_project_staff_profile_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project_staff',
        ),
    ]
