# Generated by Django 5.1.3 on 2025-02-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0072_project_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project_staff',
            new_name='projectStaff',
        ),
    ]
