# Generated by Django 5.1.3 on 2025-02-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0073_rename_project_staff_projectstaff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projectStaff',
            new_name='project_staff',
        ),
    ]
