# Generated by Django 5.1.3 on 2025-02-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0074_rename_projectstaff_project_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_staff',
            old_name='project_staff_departmernt',
            new_name='project_staff_department',
        ),
    ]
