# Generated by Django 5.1.3 on 2025-02-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0075_rename_project_staff_departmernt_project_staff_project_staff_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_staff_id', models.CharField(max_length=255, null=True)),
                ('student_staff_name', models.CharField(max_length=255, null=True)),
                ('student_guide_name', models.CharField(max_length=255, null=True)),
                ('student_staff_department', models.CharField(max_length=255, null=True)),
                ('student_join_year', models.CharField(max_length=255, null=True)),
                ('profile_status', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
