# Generated by Django 5.1.3 on 2025-02-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0076_student_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumini_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumini_staff_id', models.CharField(max_length=255, null=True)),
                ('alumini_staff_name', models.CharField(max_length=255, null=True)),
                ('alumini_staff_designation', models.CharField(max_length=255, null=True)),
                ('alumini_join_year', models.CharField(max_length=255, null=True)),
                ('profile_status', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
