# Generated by Django 5.1.3 on 2025-02-05 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0077_alumini_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumini_staff',
            old_name='alumini_join_year',
            new_name='alumini_leave_year',
        ),
    ]
