# Generated by Django 5.1.3 on 2025-02-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0079_advertise_list_circular_list_tender_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise_list',
            name='advertise_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
