# Generated by Django 5.1.3 on 2025-02-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0080_advertise_list_advertise_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular_list',
            name='circular_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
