# Generated by Django 5.1.3 on 2025-02-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0081_circular_list_circular_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular_list',
            name='circular_date',
            field=models.DateField(null=True),
        ),
    ]
