# Generated by Django 5.1.3 on 2025-02-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0083_alter_advertise_list_advertise_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender_list',
            name='tender_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
