# Generated by Django 5.1.3 on 2025-02-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0084_tender_list_tender_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical_staff',
            name='lab_department_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
