# Generated by Django 5.1.3 on 2025-02-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0085_technical_staff_lab_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical_staff',
            name='academic_background',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='technical_staff',
            name='publications',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='technical_staff',
            name='specialization',
            field=models.TextField(null=True),
        ),
    ]
