# Generated by Django 5.1.3 on 2025-02-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0086_alter_technical_staff_academic_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical_staff',
            name='professional_experience',
            field=models.TextField(null=True),
        ),
    ]
