# Generated by Django 5.1.3 on 2025-02-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0087_alter_technical_staff_professional_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_designation',
            name='department_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
