# Generated by Django 5.1.3 on 2025-02-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0088_staff_designation_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_designation',
            old_name='department_name',
            new_name='support_department_name',
        ),
    ]
