# Generated by Django 5.1.3 on 2025-02-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0089_rename_department_name_staff_designation_support_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_designation',
            name='lab_department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
