# Generated by Django 5.1.3 on 2025-02-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0090_staff_designation_lab_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_designation',
            name='lab_department_name',
        ),
    ]
