# Generated by Django 5.1.3 on 2025-02-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0091_remove_staff_designation_lab_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientific_staff',
            name='div_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
