# Generated by Django 5.1.3 on 2025-02-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0092_scientific_staff_div_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration_staff',
            name='div_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technical_staff',
            name='div_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
