# Generated by Django 5.1.3 on 2025-02-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0094_scientific_staff_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration_staff',
            name='birth_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='administration_staff',
            name='current_post_year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technical_staff',
            name='birth_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technical_staff',
            name='current_post_year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
