# Generated by Django 5.1.3 on 2025-02-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0095_administration_staff_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientific_staff',
            name='retire_year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
