# Generated by Django 5.1.3 on 2025-02-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0096_scientific_staff_retire_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientific_staff',
            old_name='current_post_year',
            new_name='current_post_date',
        ),
        migrations.RenameField(
            model_name='scientific_staff',
            old_name='join_year',
            new_name='join_date',
        ),
        migrations.RenameField(
            model_name='scientific_staff',
            old_name='retire_year',
            new_name='retire_date',
        ),
    ]
