# Generated by Django 5.1.3 on 2025-03-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0097_rename_current_post_year_scientific_staff_current_post_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administration_staff',
            old_name='current_post_year',
            new_name='current_post_date',
        ),
        migrations.RenameField(
            model_name='administration_staff',
            old_name='join_year',
            new_name='join_date',
        ),
        migrations.RenameField(
            model_name='technical_staff',
            old_name='current_post_year',
            new_name='current_post_date',
        ),
        migrations.RenameField(
            model_name='technical_staff',
            old_name='join_year',
            new_name='join_date',
        ),
        migrations.AddField(
            model_name='administration_staff',
            name='retire_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technical_staff',
            name='retire_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
