# Generated by Django 5.1.3 on 2025-03-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0098_rename_current_post_year_administration_staff_current_post_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('img', models.CharField(max_length=255, null=True)),
                ('first_look_img', models.CharField(max_length=255, null=True)),
                ('event_details', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
