# Generated by Django 5.1.3 on 2025-03-05 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0099_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
