# Generated by Django 5.1.3 on 2025-03-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0100_rename_data_created_media_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='event',
            new_name='event_name',
        ),
    ]
