# Generated by Django 5.1.3 on 2025-03-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0101_rename_event_media_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
