# Generated by Django 5.1.3 on 2025-03-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0102_media_media_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award_list',
            name='award_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
