# Generated by Django 5.1.3 on 2025-03-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0103_alter_award_list_award_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter_list',
            name='newsletter_id',
        ),
        migrations.AlterField(
            model_name='newsletter_list',
            name='newsletter_year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
