# Generated by Django 5.1.3 on 2025-03-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0105_jobappl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobappl',
            name='profilepic_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
