# Generated by Django 5.1.3 on 2025-03-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0106_alter_jobappl_profilepic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobappl',
            name='age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobappl',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobappl',
            name='ref_email_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobappl',
            name='ref_email_2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
