# Generated by Django 5.1.3 on 2025-03-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0107_alter_jobappl_age_alter_jobappl_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobappl',
            old_name='Mobile_ref_1',
            new_name='mobile_ref_1',
        ),
        migrations.RenameField(
            model_name='jobappl',
            old_name='Mobile_ref_2',
            new_name='mobile_ref_2',
        ),
        migrations.AddField(
            model_name='jobappl',
            name='fhname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
