# Generated by Django 5.1.3 on 2025-03-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0108_rename_mobile_ref_1_jobappl_mobile_ref_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin_list',
            name='bulletin_year',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
