# Generated by Django 5.1.3 on 2025-03-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0109_alter_bulletin_list_bulletin_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin_list',
            name='bulletin_id',
        ),
    ]
