# Generated by Django 5.1.3 on 2025-03-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0110_remove_bulletin_list_bulletin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications_list',
            name='publication_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
