# Generated by Django 5.1.3 on 2025-03-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0111_alter_publications_list_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='publications_list',
            name='publication_date',
            field=models.DateField(null=True),
        ),
    ]
