# Generated by Django 5.1.3 on 2025-03-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0112_alter_projects_project_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications_list',
            name='publication_author_name',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='publications_list',
            name='publication_journal_name',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='publications_list',
            name='publication_title',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
