# Generated by Django 5.1.3 on 2025-03-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0113_alter_publications_list_publication_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications_list',
            name='publication_id',
        ),
    ]
