# Generated by Django 5.1.3 on 2025-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0116_remove_publications_list_publication_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration_staff',
            name='display_order',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
