# Generated by Django 5.1.3 on 2025-03-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0117_administration_staff_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration_staff',
            name='display_order',
            field=models.IntegerField(null=True),
        ),
    ]
